### PR TITLE
Replace Material Design icons with Font Awesome

### LINKED ISSUE #13: Use Font Awesome icons for better compatibility with Vocabulary
The extension uses icons from Material Design by Google. This is evidenced here:
image

But Vocabulary has been designed with Font Awesome and even comes with some Font Awesome icons pre-packaged into the bundle. So for consistency with the rest of CC applications, Material icons should be replaced with their Font Awesome counterparts.

Font Awesome has replaced icons from The Noun Project in CC Search as well with creativecommons/cccatalog-frontend#413.

### PR DESCRIPTION
**Pull request by efl7a**
Fixes #13

**Description**
Use Font Awesome icons for better compatibility with Vocabulary

**Other information**
The spacing between header__icons is not ideal, however did not know if you wanted me to change your scss.

**Checklist:**
- [ ] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the `master` branch of the repository.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Review by makkoncept — CHANGES_REQUESTED** [review]
Hi @efl7a, thanks for this PR!
We must also adjust the sizes and padding of the icons before merging as right now it does not look good. Below is the screenshot of how the extension looks at my machine.
Browser: Chrome


Screenshot (204) (1)

**Comment by efl7a** [comment]
Currently, it looks like this.  What do you think?
Screen Shot 2019-10-04 at 11 37 57 AM

**Comment by makkoncept** [comment]
Look much better! You can push the changes.

**Comment by efl7a** [comment]
Hey @makkoncept -Sorry I missed the icons in the search and bookmark Modules.  I have fixed it, but since it is hacktoberfest, I will wait to submit a pull request to see if the people who have asked for issue #32 submit one.

**Comment by makkoncept** [comment]
No problem.
Yeah, others are working on the issue. I will let you know if we need your help with the issue in the future.
Thanks

**Pull request merged**
