### PR TITLE
Update styles of popup

### PR DESCRIPTION
**Pull request by sharmaadityaHQ**
**Fixes** #37 

**Description**
Added cc styles to paragraph and heading tags for popup.

**Other information**
Fixed typo for h3 element heading "Bookmarks"

**Checklist:**
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by sharmaaditya570191** [comment]
Hi @makkoncept sorry for late reply as the API being used for searching by the extension is being blocked by my university. Maybe this is of some help. I also fixed typo in your recent commit to change h2 "bookmarks" heading to h3.Thanks.

**Review by kroile12 — APPROVED** [review]

**Comment by makkoncept** [comment]
@sharmaaditya570191 Please also paste the screenshot.

**Comment by sharmaaditya570191** [comment]
@makkoncept I will surely update with the screenshot by tomorrow ie. Friday evening. Thanks.

**Review by kroile12 — COMMENTED** [review]
Ok

**Review by kroile12 — CHANGES_REQUESTED** [review]
V

**Comment by sharmaaditya570191** [comment]
Screenshot from 2019-12-13 19-41-38

**Comment by sharmaaditya570191** [comment]
Screenshot from 2019-12-13 20-48-42
Screenshot from 2019-12-13 20-48-58
Screenshot from 2019-12-13 20-49-12

**Comment by sharmaaditya570191** [comment]
Please have a look @makkoncept .

**Comment by makkoncept** [comment]
@sharmaaditya570191 you can look for active issues of other repositories on https://github.com/creativecommons

**Pull request merged**
