### PR TITLE
Error while downloading images in absence of content script

### LINKED ISSUE #8: Error while downloading images in absence of content script
**Describe the bug**
The following error occurs when trying to download a photo from Behance provider:
`popup.html:1 Access to XMLHttpRequest at 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/180a6536683721.5725932eb3e24.jpg' from origin 'chrome-extension://obckdhkhgdbigeihagclikjmlioanfbb' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
`
See the screenshot below.

This error is shown by some other providers also and at the same time images from some providers like Flickr, Thingiverse, Museums Victoria, etc does not give any error.

The error only occurs in chrome and opera browser while the download feature works as expected on firefox. The error goes when we set a `contents_scripts`  field in the manifest which targets at least all https web pages. I have used this as a temporary solution with an empty content script but the problem with this approach is that the extension is shown to have access to web pages and therefore a better solution is needed instead of the current hack.

**To Reproduce**
1. Build the extension
2. Remove the `content_scripts` field from chrome and opera `manifest.json`.
3. Search for any image from `Behance` provider.
4. Press the `download button`.

**Expected behavior**
The image should be downloaded without any error.

**Screenshots**
Screenshot (22)

**Desktop (please complete the following informa.tion):**
 - OS: Windows (OS Build 17763.615)
 - Browser: Chrome [Version 76.0.3809.100 (64-bit)], Opera [Version : 62.0.3331.116]
 - Version [e.g. 1.0.0]

**Additional context**
The extension uses [download.js](http://danml.com/download.html)([npm](https://www.npmjs.com/package/download)) for downloading images.

The code which handles the downloading of image and attribution can be found in [infoPopupModule.js](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/src/popup/infoPopupModule.js)

### PR DESCRIPTION
**Pull request by codingonHP**
**[Issue #8]**
The following error occurs when trying to download a photo from Behance
provider:
`popup.html:1 Access to XMLHttpRequest at 'https://mir-s3-cdn-cf.behance
.net/project_modules/max_1200/180a6536683721.5725932eb3e24.jpg' from
origin 'chrome-extension://obckdhkhgdbigeihagclikjmlioanfbb' has been
blocked by CORS policy: No 'Access-Control-Allow-Origin' header is
present on the requested resource.`

**[Cause]**
Regular web pages can use the XMLHttpRequest object to send and receive
data from remote servers, but they're limited by the same origin policy
(and since Chrome 73 content scripts are also subject to the same
restrictions as the web page they are injected into). Extensions aren't
so limited - a script executing in an extension's origin can talk to
remote servers outside of its origin, as long as the extension requests
cross-origin permissions.

**[Fix]**
Add request for permission to download images from all https:// websites
Avoids cross-site scripting vulnerabilities.
More in-depth information can be read here:
[chrome developer extension](https://developer.chrome.com/extensions/xhr)

Fixes #8 

**Developer Certificate of Origin**
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by makkoncept** [comment]
Hi @codingonHP, Thanks for the PR!

I have tested the pull request locally and the issue seems to have been solved but I am getting a warning after I downloaded a couple of images from `Wikimedia commons` which I believe were not occurring before. Can you please look into it.

Screenshot (203)

**Comment by codingonHP** [comment]
sure

**Comment by codingonHP** [comment]
Hey, I did some investigation today and found out this https://www.netsparker.com/blog/web-security/same-site-cookie-attribute-prevent-cross-site-request-forgery/ The warning is relatively new and is in process of implementation this year by chrome [?] and is still in the draft phase. What it means is that chrome will not send cookie to site if they are not marked as SameSite=None or SameSite=Secure. This is to prevent CSRF attacks from the client-side. In this extension, we do not track any user by cookie so it will not have any implications as such. This warning will eventually go away in the future version of Chrome (I am not fully sure of it though)

**Comment by makkoncept** [comment]
@codingonHP It makes more sense now. Thanks for the insight!

Can you please replicate the same changes in manifest files of opera too before we can merge. Also deleting the `content.js` file would be good.

**Comment by codingonHP** [comment]
@makkoncept Ready for merge :)

**Comment by makkoncept** [comment]
@codingonHP Thanks for taking care of webpack config 💯 . I totally forgot about it

**Pull request merged**
