### PR TITLE
Changed popup heading styles

### LINKED ISSUE #37: Change Popup heading styles (integrate CC-vocabulary)
Change the HTML markup of the heading elements of the information-popup( popup which opens when you click on image thumbnail) of the extension and integrate with cc-vocabulary.

**How to do it**
Note - CC-vocabulary is already linked into the project, therefore you just need to add the appropriate classes and mimic the markup(if different) to change the styles.

Head over to the Heading section in [CC-Vocabulary docs](https://opensource.creativecommons.org/cc-vocabulary/styleguide/#/Elements/Heading). Inspect the heading element in dev-tools and copy its classes. Adding the same classes (after removing unnecessary current ones) to the button element in the extension will change the styles.

For eg - [This element](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/src/popup/popup.html#L114) syntax should change as follows:

_Before_
```
<h3 class="attribution-label margin-bottom-small">Rich-text</h3>
```
_After_
```
<h6 class="vocab heading">Rich-text</h6>
```

**NOTE**:
- Change the tags of headings to h6 to be of the correct size.
- Remove `margin-bottom-small` class, as the heading already has some margin at the bottom.
- Also, Remove the outdated class definitions from CSS. Make sure you don't break anything, like the `.attribution-label` style definitions from [_popup.scss](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/src/popup/sass/components/_popup.scss) will not be needed after this change(therefore, remove it) but removing `margin-bottom-small` class from [utilities.scss](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/src/popup/sass/base/_utilities.scss) will surely break things.
- Only, add the styles to headings of information-popup (popup which opens after you click on image thumbnail).

### PR DESCRIPTION
**Pull request by sharmaadityaHQ**
Fixes #37 

**Description**
Changed heading styles to integrate CC-vocabulary.

**Checklist:**
- [x] My pull request has a descriptive title.
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [ ] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by makkoncept** [comment]
@sharmaaditya570191 please add the screenshot of the changes

**Comment by sharmaaditya570191** [comment]
Hi @makkoncept . I would add the screenshots in a while. Thanks.

**Comment by sharmaaditya570191** [comment]
**Before**
Screenshot from 2019-12-04 19-28-02
**After**
Screenshot from 2019-12-04 19-42-15

**Comment by makkoncept** [comment]
@sharmaaditya570191 The issue says that you have to integrate vocabulary styles to all the heading elements of the popup. You have just added it to the `attribution` tab. Please also do the same for `Info` and `Share` section.

**Review by makkoncept — CHANGES_REQUESTED** [review]

**Comment by sharmaaditya570191** [comment]
Hi @makkoncept . Do I need to change the span tags under info and share to heading tags and then add vocab classes to them?

**Comment by makkoncept** [comment]
@sharmaaditya570191 Yes! Make sure that you choose the right heading tag. I think `h6` would work. 
Also, add the vocab classes to all the paragraph tags too.

**Comment by sharmaaditya570191** [comment]
Can I close this pull request @makkoncept ? I will soon make a new PR regarding this.

**Comment by makkoncept** [comment]
@sharmaaditya570191 Okay I will close this PR.
We need to release a new version of the extension soon, so I will take this issue up.
Thanks for working on this

**Pull request closed without merging**
