### PR TITLE
Show "No Internet Connection" message

### LINKED ISSUE #10: Adding "No internet connection" message
**Is your feature request related to a problem? Please describe.**
Adding a "No internet connection" message or warning would be a good improvement.
- The loader is visible indefinitely if the user searches for something and there is no internet connection. They might not know that they are not connected to the internet.
- When viewing the bookmarks, the thumbnails and the metadata is fetched from the API. Some users might feel that all this data is saved to the extension and they don't need the internet to access them. Therefore, showing the "No internet connection" message can help. 

**Describe the solution you'd like**
The extension uses snack bar for passing messages to the user, but they disappear after 1 second and also they are very small in size. Therefore, using something that would be there until the user connects to the internet would be good, like a popup.

**Describe alternatives you've considered**
We can discuss any other effective way of showing the message.

### PR DESCRIPTION
**Pull request by sharmaadityaHQ**
Fixes #10 

**Description**
Added No Internet Connection message to extension.

**Checklist:**
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by sharmaaditya570191** [comment]
Screencast-from-Wednesday-18-December-2019-03_45_52-IST

**Review by makkoncept — CHANGES_REQUESTED** [review]
The changes still not solves the issue properly. 

- If the user checks out the bookmark section while not connected to the internet, an indefinite loading animation is shown. This should not happen.
- Imagine a situation where the user clicks the thumbnail of the image after getting disconnected to the internet. Then also they would see a popup with an indefinite loading animation. This should not happen.
- Also, as described in the issue, the "No Internet Connection" message should be shown till the user connects to the internet, and should disappear when they connect.

**Comment by sharmaaditya570191** [comment]
Yes I am just updating my PR @makkoncept . Now I have got access to unblocked internet so I can test the features properly. Thanks.

**Comment by sharmaaditya570191** [comment]
Hi @makkoncept .

I have updated my PR with the changes you suggested. Please have a look.
Also I considered 1 more case where the user is on main page and not connected to the internet. This means that "No Internet Connection" message should be displayed. Now suppose the user connects to the internet and clicks on show-bookmarks-icon so again `checkInternetConnection` to update with message "Connected to Network".  

Thanks

**Comment by sharmaaditya570191** [comment]
Hi @makkoncept . Please review this and suggest changes if any. Thanks.

**Comment by makkoncept** [comment]
@sharmaaditya570191 testing the change locally took me some time!
There is a problem with your implementation of the solution. Even if the user is connected to the internet from the very beginning of the session, unnecessary "Connected to Network" message is shown on every search. Please change this.
No, we cannot just console.log the message. The user must be notified.

**Comment by sharmaaditya570191** [comment]
@makkoncept I have updated my code now and I have found a workaround for the problem that was arising. Can you please try testing the change locally again. Thanks!

**Comment by makkoncept** [comment]
@sharmaaditya570191 It is working fine now. Thanks for working on this.

**Pull request merged**
