### PR TITLE
Update the extension landing page

### LINKED ISSUE #284: Update screenshots in landing page to new look
The [CC Search browser extension landing page](https://opensource.creativecommons.org/ccsearch-browser-extension/) still has the old look and does not include Microsoft Edge links. Please update it to be current.

### PR DESCRIPTION
**Pull request by makkoncept**
Fixes #284

**Description**
Update the landing page to reflect the new UI and feature. Also, cleaned up the markup and stylesheet.

Preview it at https://makkoncept.github.io/ccsearch-browser-extension/

**Checklist:**
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by makkoncept** [comment]
@kgodey , @panchovm Please review.

**Comment by makkoncept** [comment]
@kgodey I don't know why, but I do not see Francisco's name in "request review".

**Comment by kgodey** [comment]
@panchovm didn't have access to this project, he does now and you can request reviews from him.

**Comment by kgodey** [comment]
looks good to me! I'll defer to @panchovm on design.

**Review by kgodey — APPROVED** [review]

**Comment by panchovm** [comment]
Here my suggestions:
1. The **Go to CC Search** link will look better align to the logo, main title and descrition.
2. In the first section, the paragraph below the main title will look more readable if uses 6 columns of the grid.
3. The following four sections, where images are on left and right, should have left-align texts. Both title and description of each section.

Overall, it looks great. Clean and concise. Thank you @makkoncept

**Review by fcoveram — CHANGES_REQUESTED** [review]
I left my suggestions as a comment.

**Comment by makkoncept** [comment]
@panchovm I have incorporated the suggestions. Please review.

**Comment by panchovm** [comment]
It looks great! Thank you

**Review by fcoveram — APPROVED** [review]

**Pull request merged**
