### PR TITLE
Added the function of bookmark and unbookmark on alt clicks

### LINKED ISSUE #84: Add option to remove bookmark from main search result page
**Is your feature request related to a problem? Please describe.**
Currently an image is bookmarked from the search results if we click once on the bookmark icon and on clicking the bookmark icon it displays a message that image already bookmarked.

**Describe the solution you'd like**
Functionality of the bookmark icon button can be modified such that on 2nd click or even clicks it removes the bookmark and on 1st click or odd clicks it adds the image to the bookmark section.

Screenshot from 2020-01-16 01-00-23

(The hovered button)

### PR DESCRIPTION
**Pull request by DantrazTrev**
Fixes #84

**Description**
When the bookmark button will be clicked the image will be bookmarked if not already bookmarked else it'll be unbookmarked.

**Other information**
Changed the else condition in `src/popup/bookmarkModule.js`'s `bookmarkImage' function

**Checklist:**
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by makkoncept** [comment]
@DantrazTrev Thanks for PR. 
Before contributing, please read the [Contributing Code](https://opensource.creativecommons.org/contributing-code/) guidelines that are linked in [CONTRIBUTING.md](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/CONTRIBUTING.md). 
- It is clearly stated that you have to first comment on the issue that you want to work on and then wait for someone to assign it to you.

You don't need to close this PR and I will test and review it soon, but from next time, please adhere to the guidelines.

**Comment by makkoncept** [comment]
@DantrazTrev  It is not working on my machine. Have you tested this locally? Please add a gif or something to demonstrate the working.

**Review by makkoncept — CHANGES_REQUESTED** [review]
I have added a comment, please refer it.

**Comment by makkoncept** [comment]
@DantrazTrev a gentle ping..

**Comment by DantrazTrev** [comment]
> @DantrazTrev a gentle ping..

Sorry sir I'm kinda having internet issues in my region. I have updated and tested the PR .I am really sorry for the delay

**Comment by makkoncept** [comment]
@DantrazTrev  Please fix the linting errors.

**Review by makkoncept — CHANGES_REQUESTED** [review]
If some image is bookmarked and the user can hovers over the remove bookmark icon, the tooltip still that appears still shows "Bookmark Image". Change the title attribute to show "Remove Bookmark" as the tooltip message.
Screenshot from 2020-02-12 00-30-24
Screenshot from 2020-02-12 00-30-20

**Comment by DantrazTrev** [comment]
@makkoncept I have made all the changes requested

**Review by makkoncept — APPROVED** [review]
@DantrazTrev There was no need to update the `package.json`. Anyways, thanks for working on the issue. Merging.

**Pull request merged**
