### PR TITLE
Improves UI of Filters

### LINKED ISSUE #74: Improve UI of Filters
UI of the filter form can be improved.
Here is a suggestion: 

Screenshot from 2020-01-11 22-54-53

It also fixes #62 : Decrease spacing between search box and search results

PS: As it resolves issue #62, so, if granted permission, I want to work on it.

### PR DESCRIPTION
**Pull request by AmanR28**
Fixes #74, #62 

**Description**
Will improve the UI of filters.

**Other information**
Here is a screenshot of improved UI.

When filters are open:
Screenshot from 2020-01-11 22-54-53

When filters are closed:
Screenshot from 2020-01-12 08-37-11

**Checklist:**
- \[x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- \[x] My pull request targets the `master` branch of the repository.
- \[x] My commit messages follow [best practices][best_practices].
- \[x] I added tests for the changes I made (if applicable).
- \[x] I added or updated documentation (if applicable).
- \[x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by makkoncept** [comment]
@AmanR28 a fresh design indeed. I will test it. The two things I am concerned about is the User Experience and how the design can be extended to accommodate more filters.

**Comment by AmanR28** [comment]
@makkoncept Ohk, Waiting for results.

**Comment by makkoncept** [comment]
@AmanR28 

- The initial content is not vertically centered and it's not looking good. (please refer the screenshots below).

**Before**
Screenshot from 2020-01-13 00-46-59

**After**
Screenshot from 2020-01-13 00-46-13 (1)

- The loading message that is shown when the providers are loaded is off place. (please refer the screenshots below)

**Before**
Screenshot from 2020-01-13 00-57-07

**After**
Screenshot from 2020-01-13 00-54-27

- The intuitive action of a user after selecting the options from the drop-down is to press the apply button, without necessarily closing the dropdown. In the current implementation, the Apply button gets hidden behind the _All licences_ dropdown. A little inconvenience, but don't worry about it right now.

**Comment by AmanR28** [comment]
Filters Close:
Screenshot from 2020-01-13 17-26-44

Filters Open:
Screenshot from 2020-01-13 17-26-59

Screenshot from 2020-01-13 17-27-30

**Comment by makkoncept** [comment]
@AmanR28 works nicely! Thanks for contributing.

**Pull request merged**
