### PR TITLE
Added confirm box for Delete All button

### LINKED ISSUE #63: Add popup on clicking Delete All button under Bookmarks
**Is your feature request related to a problem? Please describe.**
There is a fair probability that the user might click the `Delete All` button under `Bookmarks` mistakenly. 

**Describe the solution you'd like**
A alert popup box which takes confirmation from the user on clicking the `Delete All` button can solve the problem.

**Additional context**
I want to work on this. Updating with a PR soon.

### PR DESCRIPTION
**Pull request by sharmaadityaHQ**
Fixes #63 

**Description**
Added confirm popup after user clicks on Delete All button in the bookmarks section.

**Checklist:**
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by sharmaaditya570191** [comment]
Screencast-from-Thursday-16-January-2020-12_16_12-IST

**Review by makkoncept — CHANGES_REQUESTED** [review]
The popup design is not consistent with rest of the extension. Please work on it.

**Comment by sharmaaditya570191** [comment]
image

**Comment by makkoncept** [comment]
@sharmaaditya570191  Please do not use any library. We don't want any unnecessary dependencies in the project. You can make the confirm popup yourself. 
- Make sure to keep it modular and reusable (eg: showNotification() utility)
- Make and use `src/popup/sass/components/_confirm_popup.scss` as the stylesheet for the component. 
- Also, uninstall the dependency _sweetalert_ and push the updated `package-lock.json`.

**Comment by sharmaaditya570191** [comment]
Sorry for period of inactivity @makkoncept . I want to close this PR as I am busy in some urgent work. Thanks.

**Pull request closed without merging**
