### PR TITLE
Updated getRequestUrl in SearchModule.js and SearchModule.test.js

### PR DESCRIPTION
**Pull request by Arunhari333**
Fixes issue #147

### CODE REVIEW

**Comment by makkoncept** [comment]
@Arunhari333 You must read the project [CONTRIBUTING.md](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/CONTRIBUTING.md) before submitting the PR. Essentially, you have to wait for someone from CC to assign you an issue before you can work on it. Anyways, I will review this PR soon.

**Comment by Arunhari333** [comment]
Sorry about that...I read CONTRIBUTING.md now. Next time I will wait till the issue is assigned to me.

**Review by makkoncept — APPROVED** [review]
@Arunhari333 Looks good! Also, please from the next time don't remove the PR template. You have to fill the appropriate sections in it and also check options under the Checklist. It helps in the review process.

**Comment by Arunhari333** [comment]
Noted

**Pull request merged**
