### PR TITLE
Align text content of the extension.

### LINKED ISSUE #85: Initial content moves to the bottom when filters are opened
**Describe the bug**  
The home page text content is moved to the bottom of the extension when filter is selected.

**To Reproduce**
1. Go to home page of extension
2. Click on filter button
3. See error

**Expected behavior**
The text content should be properly aligned in the extension.

**Screenshots**
Screenshot from 2020-01-16 01-03-45

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Version: 72.0.1

### PR DESCRIPTION
**Pull request by Dhruvi16**
Fixes #85 

**Description**

Aligns the content of the extension properly. Previously it did shift downwards when the filter button was pressed. 

**Checklist:**
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by makkoncept** [comment]
@Dhruvi16 Is the content aligned correctly? You said in the previous PR that with `11rem` space, the vertical alignment is not proper (I think you have removed that comment). Please paste a GIF showing the working.

**Comment by Dhruvi16** [comment]
Sure! I removed that comment because I realized that padding-top was 2 rem on my local repo. So the vertical alignment was distorted in that case.

**Comment by Dhruvi16** [comment]
simplescreenrecorder-2020-02-07_10 12 17

**Review by makkoncept — APPROVED** [review]
Looks good!

**Pull request merged**
