### PR TITLE
Search section does not reset when after an invalid search query(fix)

### LINKED ISSUE #124: Search section does not reset when after an invalid search query
**Describe the bug**
When the user enters a search query, the previous image thumbnails are removed from the grid. If the new query is invalid, then there are not any images to fill the grid as the API response returns a validation error. Though the user is notified that the query is invalid, the image grid is of the same size. Refer the gif below.

**To Reproduce**
1. Search for something
2. Load a couple more images.
3. Prepend ';' to the search query (this is an invalid query)

**Expected behavior**
The search section should reset to the default state.

**GIF**
ezgif com-crop

### PR DESCRIPTION
**Pull request by cristomathew**
Fixes #124 

**Description**

Updated CheckValidationError function by adding removeLoadMoreButton function and elements.gridPrimary.setAttribute function such that if error occurs the search section sets to default

**Checklist:**
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [ ] My commit messages follow best practices.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
visible errors.

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Review by makkoncept — CHANGES_REQUESTED** [review]
Please fill out the PR description and check the appropriate boxes on the checklist.

**Comment by cristomathew** [comment]
> Please fill out the PR description and check the appropriate boxes on the checklist.

is this okay?

**Comment by makkoncept** [comment]
NO, you can take a look at the other PRs.

**Comment by cristomathew** [comment]
Now?

**Comment by makkoncept** [comment]
@cristomathew Please post a gif demonstrating the working. You can use the firefox browser for this because even without the image previews, the thumbnails take a shape of considerable size.

Screenshot from 2020-02-28 19-41-03

**Comment by cristomathew** [comment]
> @cristomathew Please post a gif demonstrating the working. You can use the firefox browser for this because even without the image previews, the thumbnails take a shape of considerable size.
> 
>
i tried doing that but it seems its unable to check if the query is valid or not as it showing the same result as a valid query any idea how to solve this it happens both in chrome and firefox
Screenshot 2020-02-28 at 8 04 44 PM

**Comment by makkoncept** [comment]
Search for `+`

**Comment by cristomathew** [comment]
> Search for `+`

Tried, it just keeps on loading =>
Screenshot 2020-02-28 at 8 44 28 PM

**Comment by makkoncept** [comment]
This is the thing that the issue is all about. Instead of just loading, the search section should reset to the original state.

**Comment by cristomathew** [comment]
> This is the thing that the issue is all about. Instead of just loading, the search section should reset to the original state.

 the checkValidationError function works with the api as the parameter(fetch(url)
    .then(data => data.json())
    .then((res) => {
      checkValidationError(res);)
 but since the checkValidationError function is getting no response from the api the function itself is not being called
so i added an extra id condition just to check if the res.error_type is an input error if so do the same as Validation error and it seems to be working.

**Comment by makkoncept** [comment]
@cristomathew You can push the changes to the PR so that I can review them.

**Comment by cristomathew** [comment]
committed 

> You can push the changes to the PR so that I can review them.

done (though i don't think the if condition is necessary as if the api is working it will check input error automatically)

**Review by makkoncept — APPROVED** [review]

**Pull request merged**
