### PR TITLE
Add "Collections" section to the extension

### PR DESCRIPTION
**Pull request by makkoncept**
**Motivation**
Adding a "Collections” section to the extension would make users appreciate the sources available for them to choose from. They can explore what the sources have to offer and therefore would know what sources they should filter down if they want better results for their queries.

**Description**
The goal is to add a separate section with the display of the different sources and the ability to "search by collection".

Since CC-Vocabulary will be used for this section, the redesigning of major sections and components of the extension is inevitable for this goal. The extension currently uses a very outdated version of Vocabulary and almost everything will be updated with the new version. The adoption of CC-Vocabulary will be gradual and we need not focus on the details as the main goal is very different for this PR. For starters, I will be focusing on the Options page.

**Checklist:**
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by makkoncept** [comment]
@aldenstpage The core feature has been implemented. Please see the GIF below. I will spend the next couple of days finding and fixing edge cases and implicit bugs that might still be there. 

- The source links will be encapsulated by cards similar to the ones present in CC Search (https://search.creativecommons.org/collections) as soon as they are supported by CC-Vocabulary.
- I have yet to find a suitable icon that would represent the "Sources" section.

ezgif com-optimize (1)

**Comment by jompol63** [comment]
Source

**Comment by aldenstpage** [comment]
Fantastic! As for the source images, we hardcode those on the front end, but over time it has become increasingly apparent that the logos ought to be exposed through the API, probably through the `/v1/sources` endpoint.

**Comment by kgodey** [comment]
@aldenstpage if it makes sense for the extension, I think it would be fine to have @makkoncept do the work to add the logos to the endpoint as part of this project (if you both feel comfortable with it).

**Comment by makkoncept** [comment]
I would love to do it. It will take some time though as I am not familiar with the repository and will probably need help if I run into issues in things like setting up the environment, understanding the file structure, etc. Waiting for confirmation from @aldenstpage.

**Comment by aldenstpage** [comment]
Great, I've made a ticket for this over [here](https://github.com/creativecommons/cccatalog-api/issues/512). It doesn't seem to be possible to assign it to you, you might need to comment on the ticket first.

You can feel free to ask me any questions over Slack or we can move our weekly checkin meeting earlier.

**Comment by makkoncept** [comment]
Yes, there can be some problems as the initial objectives of the timeline are very packed up. Like this first feature took more than 2 weeks and according to the timeline, it should have been completed in 1.

**Comment by makkoncept** [comment]
@aldenstpage a gentle ping... Also, can I merge this? because the next feature builds on a lot of things that are done in this PR.

**Comment by aldenstpage** [comment]
Hey Mayank, I've reached out to you in a different channel regarding the source endpoint changes. I didn't realize this was ready for review because it still has the WIP tag (although I see it's not a draft anymore, so sorry about that).

**Review by aldenstpage — APPROVED** [review]

**Comment by makkoncept** [comment]
My bad. I didn't notice the `WIP` tag. I will be more careful in the future.

**Pull request merged**
