### PR TITLE
Implements Search to retain even after closing popup

### LINKED ISSUE #79: Search should retain even after closing popup
**Is your feature request related to a problem? Please describe.**
The search disappears if we close the popup.

**Describe the solution you'd like**
The search should be accessible for that session until changed by user.

**Additional context**
I would like to work on this.

### PR DESCRIPTION
**Pull request by AmanR28**
Fixes #79 

**Description**
Stores search data to local storage.

**Other information**
For performance: It loads different pages of a search when needed, not the whole search at once.

**Checklist:**
- \[x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- \[x] My pull request targets the `master` branch of the repository.
- \[x] My commit messages follow [best practices][best_practices].
- [x] I added tests for the changes I made (if applicable).
- \[x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by AmanR28** [comment]
@makkoncept Please review it.

**Comment by makkoncept** [comment]
@AmanR28 one problem that immediately popped up was the appending of multiple loaders at the bottom of the grid (screenshot below). 
I think moving on from lazy loading during scrolling was long overdue. A better alternative would be a "Load more" button at the bottom of the grid. I think we should first implement this and then mold this PR accordingly (as the other way round would be error-prone).  Let me resolve this first.

Screenshot from 2020-01-17 16-18-57 (1)

**Comment by AmanR28** [comment]
Yep "Load more" option will be much better there.

I am just uploading some code to fix that infinite bar, which might create an issue if the user tries to drag down after pressing "Load More" Button.
Sir, should i keep it this fix of infinite part here, or i should revert it if it will be better to show it fixed on #89.
I will revert it if it is not fine here. Please guide me.

**Comment by AmanR28** [comment]
@makkoncept  Can this be merged now, please?

**Comment by makkoncept** [comment]
Before it, some work needs to be done. I will let you know of any further developments.

**Comment by makkoncept** [comment]
@AmanR28 infinite scrolling has been removed in #96. You can see that this has caused some merge conflicts. Feel free to close this and make a fresh PR to solve the issue in the context of new changes.

 Also, you don't need to save so much information in the localStorage. The storing page number is absolutely not needed. We don't want the user to wait for the extension to load dozens of pages (that they may have scrolled to earlier) before they can make a new query.

**Comment by AmanR28** [comment]
> @AmanR28 infinite scrolling has been removed in #96. You can see that this has caused some merge conflicts. Feel free to close this and make a fresh PR to solve the issue in the context of new changes.

I will do that ASAP.


> Also, you don't need to save so much information in the localStorage. The storing page number is absolutely not needed. We don't want the user to wait for the extension to load dozens of pages (that they may have scrolled to earlier) before they can make a new query.

I have considered that point and kept the performance of the application in mind. I am not loading all the stored at once, but when the user wants (by scrolling down).
I have just updated the "nextPage" function first to check whether the query result that the user wants to get is already stored or not. If the result is already stored (i.e., it was user's last search, then yes), then use that result instead of making a new query to the server, hence speeding up the process and implementing that feature.

Summary: Storing each page, as a result, serves as cache, hence :
1. Implementing Store Last Search Feature.
2. Speeding up the process of showing the result to the user.
3. Preventing unnecessary repeated requests to server.

<> I will implement this feature ASAP <>

**Comment by AmanR28** [comment]
@makkoncept  Can I reset my branch back to master and pull updated master and then push the code here.
So that the feature can be implemented in this pr itself.

**Comment by makkoncept** [comment]
It would be better if you open a new PR. You can close this one.

**Comment by AmanR28** [comment]
ohk sir

**Pull request closed without merging**
