### PR TITLE
Integrate CC Vocabulary into the extension

### PR DESCRIPTION
**Pull request by makkoncept**
**Description**

This PR integrates vocabulary by replacing the custom design components of the extension with that of vocabulary. The User interface of this integration will be guided by [CC Browser Extension Mockup](https://www.figma.com/file/nJk4krHryIjzYGvaioMsAu/Browser-extension?node-id=892%3A4562).

**Checklist:**
- [ ] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the `master` branch of the repository.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by makkoncept** [comment]
Hi @panchovm. Most parts of the Extension mockup design has been integrated. I am pasting a link to a brief demo that shows how it's looking. Please review these. Some notable differences between the implementation and the mockup designs are:
- "Export all Bookmarks" button instead of "Export Selected". The extension now supports only the former option because we have increased the number of bookmarks and notable lag is observed when trying to select and export a large number of bookmarks.
- Use the name of the source instead of the icon in the information tab of the image-detail.
- Many assumptions for the dark-mode of image-detail and sources section. I'll correct them after their mockup designs are finalized.

Default - https://vimeo.com/449694519
Dark mode - https://vimeo.com/449702732

cc @aldenstpage, @kgodey, @zackkrida, @annatuma 

Suggestions and improvements are most welcome :)

**Comment by makkoncept** [comment]
I should mention that some workflows are yet to be implemented. A couple of them is search by image tag and stacking and unstacking of multiple image-detail views. Also, there are good numbers of bugs present. 

I am working on the above-mentioned issues.

**Comment by zackkrida** [comment]
@makkoncept I think it looks _great_. Nice work. I'll defer to @panchovm for specific design feedback

**Comment by panchovm** [comment]
@makkoncept, it looks great! I really like it. Regarding your points:
1. I understand. Now seeing it live, I think we should move the `Export all Bookmarks` out of editing action, on the left side of the screen. See the mockup below.
2. Perfect. That's the layout we are using for future single result pages.
3. I will work on those mockups and will back to you.

And two suggestions:
1. The arrow inside the `back to top` action looks odd because it's not aligned correctly. I will fix that in the mockup.
2. I am not completely convinced about the term **export**. For me, it's more familiar for tech users. It is more clear to say **download** (Download all bookmarks). What are your thoughts on this?

Despite the points mentioned above, it looks wonderful. Thank you again. 

## Mockup
Screen Shot 2020-08-20 at 11 46 02

**Comment by zackkrida** [comment]
> I am not completely convinced about the term export.

In my opinion "export" _is_ a technical term, but exporting _is_ a technical act. If users understand what they are doing and why when they hit "export" they should be familiar with the term. I worry "download" implies that _images_ are being downloaded.

**Comment by makkoncept** [comment]
@panchovm Actually it downloads a `json` file which contains the information about the bookmarks. This feature can be used for archiving, sharing, or saving the bookmarks. The bookmark file can be imported from the options page.

**Comment by kgodey** [comment]
I think "Export" makes more sense for this, which is a machine-readable file containing bookmark information.

**Comment by makkoncept** [comment]
@panchovm a demo of the "export" feature.
sample

**Comment by panchovm** [comment]
Export makes completely sense. Thanks

**Comment by panchovm** [comment]
Hey @makkoncept, [here is the dark mode](https://www.figma.com/file/nJk4krHryIjzYGvaioMsAu/Browser-extension?node-id=1500%3A58&viewport=60%2C183%2C0.2084934413433075) of all mockups with the changes mentioned. I didn't update the white mode mockups since are style changes and should apply to both versions.

**Comment by makkoncept** [comment]
@panchovm They look very good. I'll make the required changes. Thanks!

**Comment by makkoncept** [comment]
There is still some work left but logically it's not related to the theme of this PR which is to integrate the design mockup and CC Vocabulary. I'll open a different PR for it.

**Pull request merged**
