### PR TITLE
Decrease space between home page content and filters

### LINKED ISSUE #85: Initial content moves to the bottom when filters are opened
**Describe the bug**  
The home page text content is moved to the bottom of the extension when filter is selected.

**To Reproduce**
1. Go to home page of extension
2. Click on filter button
3. See error

**Expected behavior**
The text content should be properly aligned in the extension.

**Screenshots**
Screenshot from 2020-01-16 01-03-45

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Version: 72.0.1

### PR DESCRIPTION
**Pull request by Dhruvi16**
Fixes #85 

**Description**

**Other information**

**Checklist:**
- [ ] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the `master` branch of the repository.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by Dhruvi16** [comment]
Yes! I tried doing adding ` position: absolute` but it is not working. It still moves downwards when the filter button is clicked. And I am having trouble in inspecting the addon in firefox. As soon as I try expanding one of the classes the addon goes away. Can you help me there? so I can figure out what can fix this.

**Comment by makkoncept** [comment]
Yeah, debugging on firefox is not intuitive. You can follow the following steps:

- Go to the window where you load temporary addon and click on the `Inspect` button.
Screenshot (266)

- A new tab will open with firefox debugger. Notice that DOM will be loaded only when you have opened the extension. But before that, click on the three dots on the top right corner and select the option `Disable Popup Auto-hide`.
Screenshot (267)

- Now click on the CC extension icon to open it. It will not close down when you click anywhere outside and thus, you can easily debug. To close the extension, press the `esc` key.
Screenshot (268)

_Side Note:_ Debugging on Chrome is relatively straightforward - just right click the on the extension and click `Inspect` option.

**Comment by Dhruvi16** [comment]
image
image
Hey! I was able to fix the problem by changing the position of filter to fixed from relative but as it requires space there is a need for extra space between the search bar and the content.

**Comment by makkoncept** [comment]
@Dhruvi16 Issue can be solved without disturbing the filters. As I have said above, giving `position: absolute` to the content seems to be working. 
I tried it real quick by adding the following rule to the initial content from the developer console.
```
position: absolute;
top: 11rem;
```
ezgif com-crop (1)

**Comment by Dhruvi16** [comment]
I am not sure how that is working because this is what I am getting
ccextension

**Comment by Dhruvi16** [comment]
image
Ok this works! But I am not sure about 11 rem. As in my system it looks like this. How about `top: 40%`?

**Comment by makkoncept** [comment]
Predecessor of #127.

**Pull request closed without merging**
